# Generated by Django 5.2.9 on 2025-12-03 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_restoran', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('deskripsi', models.TextField(blank=True)),
                ('jam_buka', models.TimeField()),
                ('jam_tutup', models.TimeField()),
                ('status_buka', models.BooleanField(default=True)),
                ('foto_logo', models.ImageField(blank=True, null=True, upload_to='logo_restoran/')),
                ('kategori', models.CharField(blank=True, help_text='Contoh: Ayam, Kopi, Burger, dll', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
