# Generated by Django 5.2.9 on 2025-12-03 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurantprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_makanan', models.ImageField(blank=True, null=True, upload_to='foto_makanan/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out')], default='available', max_length=20)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurantprofile')),
            ],
        ),
    ]
