# Generated by Django 5.2.9 on 2025-12-03 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField(blank=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profil_customer/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_telepon', models.CharField(max_length=15)),
                ('plat_kendaraan', models.CharField(max_length=20)),
                ('jenis_kendaraan', models.CharField(max_length=50)),
                ('status_aktif', models.BooleanField(default=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profil_driver/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
