# Generated by Django 5.2.9 on 2025-12-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_menu_restaurant'),
        ('restaurant', '0003_menu_alter_cartitem_menu_alter_orderitem_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
