# Generated by Django 5.2.9 on 2025-12-04 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('processing', 'Diproses'), ('ready', 'Siap Diambil'), ('on_delivery', 'Dalam Pengiriman'), ('completed', 'Selesai')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_harga',
            field=models.IntegerField(),
        ),
    ]
